name: Build Read Log
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
permissions:
  contents: write
  issues: read
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Read-and-Understood.md
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.READLOG_TOKEN }}
          script: |
            const fs = require('fs');
            const owner = 'LYO-X';
            const repo = 'read-logs';

            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              { owner, repo, labels: 'read', state: 'all', per_page: 100 }
            );

            const linesFromBody = (body) => body.split('\n').map(s => s.trim());
            const extractAfterHeading = (lines, heading) => {
              const idx = lines.findIndex(l => l.toLowerCase() === `### ${heading.toLowerCase()}`);
              return (idx !== -1 && lines[idx + 1]) ? lines[idx + 1].trim() : '';
            };

            const rows = issues.map(i => {
              const lines = linesFromBody(i.body || '');
              const url = extractAfterHeading(lines, 'Document URL');
              const ver = extractAfterHeading(lines, 'Version / commit (optional)');
              const who = i.user?.login ? `@${i.user.login}` : 'unknown';
              const date = (i.created_at || '').slice(0,10);
              const titleUrl = (i.title || '').replace(/^Read:\s*/i,'').trim();
              const link = url || titleUrl;
              return `- ${date} — ${who} read ${link}${ver ? ` (version ${ver})` : ''} [#${i.number}](https://github.com/${owner}/${repo}/issues/${i.number})`;
            });

            const header = `# Read-and-Understood\n\nThis page lists read acknowledgements submitted via ${owner}/${repo}.\n`;
            const md = `${header}\n${rows.join('\n')}\n`;
            fs.writeFileSync('Read-and-Understood.md', md);

      - name: Commit updates
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add Read-and-Understood.md
            git commit -m "Update Read-and-Understood.md"
            git push
          fi
