name: Build Read Log

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

permissions:
  contents: write
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Read-and-Understood.md
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.READLOG_TOKEN }}  # PAT with Issues: Read for LYO-X/read-logs
          script: |
            const fs = require('fs');
            const owner = 'LYO-X';
            const repo = 'read-logs';

            // Fetch all issues labeled 'read' from the read-logs repo
            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              { owner, repo, labels: 'read', state: 'all', per_page: 100 }
            );

            // Parse Issue Form body: read the line AFTER the "### ..." heading
            function parseFields(body) {
              const lines = (body || '').split('\n').map(s => s.trim());
              const extractAfterHeading = (heading) => {
                const idx = lines.findIndex(l => l.toLowerCase() === `### ${heading.toLowerCase()}`);
                return (idx !== -1 && lines[idx + 1]) ? lines[idx + 1].trim() : '';
              };
              return {
                url: extractAfterHeading('Document URL'),
                ver: extractAfterHeading('Version / commit (optional)')
              };
            }

            // Build the Markdown rows
            const rows = issues.map(i => {
              const { url, ver } = parseFields(i.body);
              const who = i.user?.login ? `@${i.user.login}` : 'unknown';
              const date = (i.created_at || '').slice(0,10);
              // Fallback if the form was bypassed: use the URL in the title after "Read:"
              const titleUrl = (i.title || '').replace(/^Read:\s*/i,'').trim();
              const link = url || titleUrl;
              return `- ${date} — ${who} read ${link}${ver ? ` (version ${ver})` : ''} [#${i.number}](https://github.com/${owner}/${repo}/issues/${i.number})`;
            });

            // Write the output file
            const header = `# Read-and-Understood\n\nThis page lists read acknowledgements submitted via ${owner}/${repo}.\n`;
            const md = `${header}\n${rows.join('\n')}\n`;
            fs.writeFileSync('Read-and-Understood.md', md);

      - name: Commit updates
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add Read-and-Understood.md
            git commit -m "Update Read-and-Understood.md"
            git push
          fi
